# Generated by Django 5.2.2 on 2025-06-08 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccount',
            name='dob',
        ),
        migrations.RemoveField(
            model_name='useraccount',
            name='mobile',
        ),
    ]
