# Generated by Django 5.2.2 on 2025-06-11 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_remove_useraccount_dob_remove_useraccount_mobile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Transfer',
        ),
    ]
