# Generated by Django 5.2.2 on 2025-06-11 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_delete_transfer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deposit',
            name='deposit_date',
        ),
        migrations.RemoveField(
            model_name='withdraw',
            name='withdraw_date',
        ),
    ]
